# This file was generated by GoReleaser. DO NOT EDIT.
class Jcconv < Formula
  desc "An offline simplified <-> traditional (HK + TW) Chinese converter (with api server)."
  homepage "https://github.com/jackytck/jcconv"
  version "1.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jackytck/jcconv/releases/download/v1.0.3/jcconv_1.0.3_Darwin_x86_64.tar.gz"
    sha256 "ebeab379058cf16ed8213333c06b3aa545451cbc11037eae74e645ffe2e10ea9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jackytck/jcconv/releases/download/v1.0.3/jcconv_1.0.3_Linux_x86_64.tar.gz"
      sha256 "b8231ff422dc3a4ff9c0b692ad832d13ecc05baf29aa4514c980a0bee5ba4e06"
    end
  end

  def install
    bin.install "jcconv"
  end

  test do
    system "#{bin}/jcconv version"
  end
end
